### ISSUE TITLE
Browse Nodes dropdown cutoff

### ISSUE THREAD

**Issue by wwells** [uc-cdis/data-portal#134]
Firefox and Chrome - both have cutoff of dropdown menu.  
<img width="782" alt="screen shot 2017-09-13 at 8 06 49 pm" src="https://user-images.githubusercontent.com/5175497/30407753-cb0c73c8-98bf-11e7-9aeb-7bbcb8d6d43e.png">

**Comment by philloooo** [comment]
resolved by #143
