### ISSUE TITLE
check if need to refresh session for all api calls

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/data-portal#211]
fence sets up two cookies (after uc-cdis/fence#37 is merged):
an access_token cookie and a session_token cookie.
The default TTL for access_token is 10 min, it's a stateless token(we can't revoke it) so the TTL need to be short. The default TTL for session cookie is 30min for stale session and 8h max life time (settings here )

Whenever fence is hit, it will refresh session token if the lifetime is < 8h, and also create a new access_token if the old one is expired but the session is not expired yet.
On the user end though, any action to any api count as a 'user activity', so even if it hits sheepdog it should also refresh the session.

So we should
- wrap our non-fence api calls to handle that when the response code is 401/403, call fence /user endpoint, which will refresh the session, if fence also return 401/403, that means the session is actually expired, should pop up the login window, if it's 200, redo the previous api call.
- remove the [setinterval](https://github.com/uc-cdis/data-portal/blob/master/src/index.jsx#L40) that call fence every minute

**Comment by trevars** [comment]
Estimate 6.

**Comment by thanh-nguyen-dang** [comment]
spent 8 hours
