### ISSUE TITLE
support having multiple login options

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/data-portal#228]
support commons that want to enable logging in through multiple identity providers
Genomel wants to support google login, nih login and InCommons eduGain login

spent 8 hours

**Comment by trevars** [comment]
Priority for GenoMEL is to add google login.

**Comment by philloooo** [comment]
Need to support this for kids first too so that it's not hardcoded to google login

**Comment by philloooo** [comment]
This will query the fence endpoint `/login` endpoint to get all available login options

**Comment by thanh-nguyen-dang** [comment]
spent 12 hours including
- fixing bug in fence
- setup dev testing environment
- testing in dev testing environment
