### ISSUE TITLE
wrong links in project diagrams when multiple alternative parents

### ISSUE THREAD

**Issue by fortuno** [uc-cdis/data-portal#244]
When a node has alternative links, the diagram always shows links to all the possible parent nodes even when all entities only link to one of the alternatives. Example: 

https://niaid.bionimbus.org/ndh-dmid-LHV (entities in Laboratory Result Summary only connect to Sample in this project but it still shows a link to Follow Up)

**Comment by philloooo** [comment]
a related bug:
links are screwed up in https://data.braincommons.org/mjff-LRRK2 some nodes do not show up until you toggle the view
