### ISSUE TITLE
PXD-348 ⁃ Design -> GUID landing page

### ISSUE THREAD

**Issue by gneglur** [uc-cdis/data-portal#275]
Index documents with size of hash and location. Need a UI for when someone has a Gen3 ID that shows you to download the data.

┆Attachments: <a href="https:&#x2F;&#x2F;jira.opensciencedatacloud.org&#x2F;secure&#x2F;attachment&#x2F;17371&#x2F;zip.png">zip.png</a>

**Comment by philloooo** [comment]
example landing page: http://minid.bd2k.org/minid/landingpage/ark:/57799/b94x3r

**Comment by zflamig** [comment]
More examples 

https://doi.pangaea.de/10.1594/PANGAEA.887718

https://www.hydroshare.org/resource/6ee06abb2ed8414f9b66d229c8e9a129/

https://catalog.data.gov/dataset/state-drug-utilization-data-2017

https://data.cdc.gov/Pregnancy-Vaccination/State-Specific-Influenza-Vaccination-Coverage-Amon/mmi4-8ajr

https://edg.epa.gov/metadata/catalog/search/resource/details.page?uuid={B9CB1E5B-21D4-4DBD-A38F-22BF3C5A1BDF}

**Comment by philloooo** [comment]
➤ Vivi commented:

file location
https://uchicago.app.box.com/folder/50585955144
